######################## default configuration ####################
baseURL = "/"
title = "Platzhalter Gaming"
theme = "omega-hugo"
# google analytics
googleAnalytics = "" # example : UA-123-45
[markup.goldmark.renderer]
unsafe = true

######################### navigation ##############################

#[[menu.main]]
#name = "Home"
#pre = ""
#url = "/"
#weight = 1

[[menu.main]]
name = "Live Map"
pre = ""
url = "https://map.platzhalter-gaming.net/"
weight = 3

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "70px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
contact_info = ""
# Preloader
preloader = true
# google map
[params.map]
enable = false
gmap_api = ""
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
map_marker = "images/map-marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social site ########################
[[params.social]]
title = "github"
icon = "fa-github" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://github.com/platzhalter-gaming"
